log: upload to releases

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -44,18 +44,12 @@ jobs:
       - name: Create archive
         run: |
           echo "Current BINARY_NAME: $BINARY_NAME"
-          echo "Current VERSION: $VERSION"
           echo "Target path: target/release/$BINARY_NAME"
-
-          # Check if the binary exists (add this check)
-          if [ -f "target/release/$BINARY_NAME" ]; then
-            tar -czvf "${BINARY_NAME}-${VERSION}.tar.gz" "target/release/$BINARY_NAME"
-            echo "Archive created: ${BINARY_NAME}-${VERSION}.tar.gz"
-            mv "${BINARY_NAME}-${VERSION}.tar.gz" artifacts/release-artifacts/${{ github.sha }}
-          else
-            echo "Error: Binary not found at target/release/$BINARY_NAME"
+          tar -czvf "artifacts/release-artifacts/${{ github.sha }}/${BINARY_NAME}-${VERSION}.tar.gz" "target/release/$BINARY_NAME" || {
+            echo "Error: Could not create archive. Stopping workflow."
             exit 1
-          fi
+          }
+          echo "Archive created: artifacts/release-artifacts/${{ github.sha }}/$BINARY_NAME-$VERSION.tar.gz"
 
       - name: Upload artifact
         uses: actions/upload-artifact@v3
@@ -63,7 +57,7 @@ jobs:
           name: release-artifacts
           path: "artifacts/release-artifacts/${{ github.sha }}/${{ env.BINARY_NAME}}-${{ env.VERSION}}.tar.gz"
 
-      - name: Upload artifact to release (optional)
+      - name: Upload artifact to release
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
